apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: zeek
  name: zeek
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zeek
    spec:
      containers:
      - args:
        - -i
        - af_packet::eth0
        - local
        image: blacktop/zeek:elastic
        name: zeek
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_RAW
        volumeMounts:
        - mountPath: /pcap
          name: zeek-claim0
      
       
      restartPolicy: Always
      volumes:
      - name: zeek-claim0
        persistentVolumeClaim:
          claimName: zeek-claim0
status: {}
